services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medici
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -d postgres://postgres:postgres@db:5432/medici -c 'SELECT 1;' || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  medici-server:
    image: mrkaye97/medici-server:latest
    env_file: ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  medici-frontend:
    image: mrkaye97/medici-frontend:latest
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - medici-server
    restart: unless-stopped

volumes:
  postgres_data:
