/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "../pages/__root";
import { Route as SignupImport } from "../pages/signup";
import { Route as LoginImport } from "../pages/login";
import { Route as FriendsImport } from "../pages/friends";
import { Route as IndexImport } from "../pages";
import { Route as PoolsPoolIdImport } from "../pages/pools.$poolId";

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const FriendsRoute = FriendsImport.update({
  id: "/friends",
  path: "/friends",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const PoolsPoolIdRoute = PoolsPoolIdImport.update({
  id: "/pools/$poolId",
  path: "/pools/$poolId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/friends": {
      id: "/friends";
      path: "/friends";
      fullPath: "/friends";
      preLoaderRoute: typeof FriendsImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupImport;
      parentRoute: typeof rootRoute;
    };
    "/pools/$poolId": {
      id: "/pools/$poolId";
      path: "/pools/$poolId";
      fullPath: "/pools/$poolId";
      preLoaderRoute: typeof PoolsPoolIdImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/friends": typeof FriendsRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/pools/$poolId": typeof PoolsPoolIdRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/friends": typeof FriendsRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/pools/$poolId": typeof PoolsPoolIdRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/friends": typeof FriendsRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/pools/$poolId": typeof PoolsPoolIdRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/friends" | "/login" | "/signup" | "/pools/$poolId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/friends" | "/login" | "/signup" | "/pools/$poolId";
  id: "__root__" | "/" | "/friends" | "/login" | "/signup" | "/pools/$poolId";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FriendsRoute: typeof FriendsRoute;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
  PoolsPoolIdRoute: typeof PoolsPoolIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  PoolsPoolIdRoute: PoolsPoolIdRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/friends",
        "/login",
        "/signup",
        "/pools/$poolId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/friends": {
      "filePath": "friends.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/pools/$poolId": {
      "filePath": "pools.$poolId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
